name: Build and release

on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    
    outputs:
      new-version: ${{ steps.auto-version.outputs.new-version }} 

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Check linting
        run: npm run lint-ci

      - name: Run tests
        run: npm run test --if-present

        # Workaround as GitHub doesn't support using private actions
      - name: Checkout action
        uses: actions/checkout@v2.3.4
        with:
          token: ${{ secrets.PAT }}
          repository: needssoysauce/auto-version
          path: auto-version

      - name: Configure git
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Update version
        id: auto-version
        uses: ./auto-version
        with:
          major: |
            feat!
            fix!
          minor: |
            feat
          patch: |
            fix
          seperator: ":"
          token: ${{ github.token }}
          message: "Update version to %s"
          no-prefix: "success"
          git-tag-version: "true"

      - if: steps.auto-version.outputs.new-version != ''
        run: git push --follow-tags

      - if: steps.auto-version.outputs.new-version != ''
        run: npm run build

      - name: Upload artifact
        if: steps.auto-version.outputs.new-version != ''
        uses: actions/upload-artifact@v2.2.4
        with:
          name: build
          path: |
            dist
            package.json
            README.md
            LICENSE

  release:
    needs: build
    runs-on: ubuntu-latest
    if: needs.build.outputs.new-version != ''
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@needssoysauce"

      - name: Download a Build Artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: build
          path: build

      - run: npm publish build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
